print("Hello")
print("David Emmanuel Osekwe")
print(25)
print(7 + 3)
print("I am a Boy \nI need Money")
print("'Python' is fun")
print("David\tEmmanuel\tOsekwe")
print("I am learning Python")
print("\t*")
print()
print("*\t*\t*")
print("Coding is fun!")
